const donneesProduits = [
  {
    "id": "00001",
    "nom": "Miroir Soleil",
    "description": "Miroir mural doré en forme de soleil",
    "prix": 45.99,
    "type": "miroir",
    "style": "bohème",
    "piece": "salon",
    "materiau": "métal",
    "solde": 10
  },
  {
    "id": "00002",
    "nom": "Vase Céramique Blanche",
    "description": "Vase minimaliste pour fleurs séchées",
    "prix": 25.5,
    "type": "vase",
    "style": "scandinave",
    "piece": "chambre",
    "materiau": "céramique",
    "solde": 0
  },
  {
    "id": "00003",
    "nom": "Suspension Rotin",
    "description": "Suspension naturelle en rotin",
    "prix": 65,
    "type": "lampe",
    "style": "bohème",
    "piece": "salon",
    "materiau": "rotin",
    "solde": 15
  },
  {
    "id": "00004",
    "nom": "Horloge Bois Naturel",
    "description": "Horloge design scandinave",
    "prix": 30,
    "type": "horloge",
    "style": "scandinave",
    "piece": "cuisine",
    "materiau": "bois",
    "solde": 5
  },
  {
    "id": "00005",
    "nom": "Bougeoir Marbre",
    "description": "Bougeoir chic en marbre noir",
    "prix": 18.75,
    "type": "bougeoir",
    "style": "minimaliste",
    "piece": "salle à manger",
    "materiau": "marbre",
    "solde": 0
  },
  {
    "id": "00006",
    "nom": "Tapis Berbère",
    "description": "Tapis en laine style berbère",
    "prix": 120,
    "type": "tapis",
    "style": "ethnique",
    "piece": "salon",
    "materiau": "laine",
    "solde": 20
  },
  {
    "id": "00007",
    "nom": "Étagère Flottante",
    "description": "Étagère murale bois clair",
    "prix": 35.9,
    "type": "étagère",
    "style": "scandinave",
    "piece": "entrée",
    "materiau": "bois",
    "solde": 0
  },
  {
    "id": "00008",
    "nom": "Cadre Doré",
    "description": "Cadre photo doré 10x15 cm",
    "prix": 12.99,
    "type": "cadre",
    "style": "classique",
    "piece": "bureau",
    "materiau": "métal",
    "solde": 0
  },
  {
    "id": "00009",
    "nom": "Plante Artificielle",
    "description": "Plante verte artificielle en pot",
    "prix": 22,
    "type": "plante",
    "style": "moderne",
    "piece": "salle de bain",
    "materiau": "plastique",
    "solde": 10
  },
  {
    "id": "00010",
    "nom": "Statue Visage",
    "description": "Objet décoratif abstrait en céramique",
    "prix": 27.49,
    "type": "sculpture",
    "style": "moderne",
    "piece": "salon",
    "materiau": "céramique",
    "solde": 0
  },
  {
    "id": "00011",
    "nom": "Lampe Tripode",
    "description": "Lampe trépied au design industriel",
    "prix": 89.99,
    "type": "lampe",
    "style": "industriel",
    "piece": "bureau",
    "materiau": "métal",
    "solde": 5
  },
  {
    "id": "00012",
    "nom": "Tapis Rond Beige",
    "description": "Tapis doux et rond pour chambre",
    "prix": 79.5,
    "type": "tapis",
    "style": "minimaliste",
    "piece": "chambre",
    "materiau": "coton",
    "solde": 0
  },
  {
    "id": "00013",
    "nom": "Coussin Terracotta",
    "description": "Coussin déco en lin terracotta",
    "prix": 15.99,
    "type": "coussin",
    "style": "bohème",
    "piece": "salon",
    "materiau": "lin",
    "solde": 10
  },
  {
    "id": "00014",
    "nom": "Panier Osier",
    "description": "Panier de rangement en osier tressé",
    "prix": 23,
    "type": "panier",
    "style": "naturel",
    "piece": "entrée",
    "materiau": "osier",
    "solde": 0
  },
  {
    "id": "00015",
    "nom": "Horloge Murale Noire",
    "description": "Horloge moderne en métal noir",
    "prix": 33,
    "type": "horloge",
    "style": "moderne",
    "piece": "cuisine",
    "materiau": "métal",
    "solde": 5
  },
  {
    "id": "00016",
    "nom": "Tabouret Velvet",
    "description": "Tabouret rembourré en velours vert",
    "prix": 49,
    "type": "siège",
    "style": "classique",
    "piece": "chambre",
    "materiau": "velours",
    "solde": 10
  },
  {
    "id": "00017",
    "nom": "Table Basse Bois Clair",
    "description": "Petite table basse ronde",
    "prix": 99,
    "type": "table",
    "style": "scandinave",
    "piece": "salon",
    "materiau": "bois",
    "solde": 0
  },
  {
    "id": "00018",
    "nom": "Lanterne Métal Doré",
    "description": "Lanterne décorative avec poignée",
    "prix": 29.5,
    "type": "lanterne",
    "style": "classique",
    "piece": "terrasse",
    "materiau": "métal",
    "solde": 0
  },
  {
    "id": "00019",
    "nom": "Rideaux Blancs",
    "description": "Paire de rideaux blancs légers",
    "prix": 40,
    "type": "rideaux",
    "style": "minimaliste",
    "piece": "chambre",
    "materiau": "coton",
    "solde": 5
  },
  {
    "id": "00020",
    "nom": "Affiche Abstraite",
    "description": "Poster déco art abstrait beige et noir",
    "prix": 14.99,
    "type": "affiche",
    "style": "moderne",
    "piece": "salon",
    "materiau": "papier",
    "solde": 0
  },
  {
    "id": "00021",
    "nom": "Miroir Ovale",
    "description": "Miroir mural avec cadre en bois",
    "prix": 55,
    "type": "miroir",
    "style": "naturel",
    "piece": "entrée",
    "materiau": "bois",
    "solde": 10
  },
  {
    "id": "00022",
    "nom": "Porte-Manteau Trépied",
    "description": "Porte-manteau moderne métal et bois",
    "prix": 89,
    "type": "porte-manteau",
    "style": "moderne",
    "piece": "entrée",
    "materiau": "métal",
    "solde": 0
  },
  {
    "id": "00023",
    "nom": "Boîte de Rangement",
    "description": "Boîte tissu pliable pour étagère",
    "prix": 9.99,
    "type": "boîte",
    "style": "minimaliste",
    "piece": "bureau",
    "materiau": "tissu",
    "solde": 0
  },
  {
    "id": "00024",
    "nom": "Tapis Motif Géométrique",
    "description": "Tapis déco avec formes modernes",
    "prix": 110,
    "type": "tapis",
    "style": "moderne",
    "piece": "salle à manger",
    "materiau": "polypropylène",
    "solde": 15
  },
  {
    "id": "00025",
    "nom": "Guirlande LED",
    "description": "Guirlande lumineuse ambiance cosy",
    "prix": 19.5,
    "type": "luminaire",
    "style": "bohème",
    "piece": "chambre",
    "materiau": "plastique",
    "solde": 0
  },
  {
    "id": "00026",
    "nom": "Suspension Verre Fumé",
    "description": "Lampe suspendue avec verre teinté",
    "prix": 75,
    "type": "lampe",
    "style": "industriel",
    "piece": "salle à manger",
    "materiau": "verre",
    "solde": 10
  },
  {
    "id": "00027",
    "nom": "Coussin Graphique",
    "description": "Coussin déco noir et blanc",
    "prix": 17.99,
    "type": "coussin",
    "style": "moderne",
    "piece": "salon",
    "materiau": "coton",
    "solde": 0
  },
  {
    "id": "00028",
    "nom": "Bibliothèque Étagères Ouvertes",
    "description": "Grande étagère en bois clair",
    "prix": 160,
    "type": "étagère",
    "style": "scandinave",
    "piece": "bureau",
    "materiau": "bois",
    "solde": 20
  },
  {
    "id": "00029",
    "nom": "Miroir Rond Noir",
    "description": "Miroir rond avec cadre fin noir",
    "prix": 42,
    "type": "miroir",
    "style": "moderne",
    "piece": "salle de bain",
    "materiau": "métal",
    "solde": 5
  },
  {
    "id": "00030",
    "nom": "Banc d’entrée Rangement",
    "description": "Banc en bois avec paniers de rangement",
    "prix": 135,
    "type": "banc",
    "style": "naturel",
    "piece": "entrée",
    "materiau": "bois",
    "solde": 0
  }
];

export default donneesProduits;
